//
// Created by LN on 2021/3/11.
//

#ifndef UDP_PLAYER_SERVER_C_RESULTCODE_H
#define UDP_PLAYER_SERVER_C_RESULTCODE_H

#define  RESULT_OK  1
#define  RESULT_ERROR  0
#endif //UDP_PLAYER_SERVER_C_RESULTCODE_H
